cargo-features = ["edition2024"]

[package]
description = "A tool to change line endings in files."
edition = "2024"
name = "newl"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
clap = {version = "4.5", features = ["cargo"]}
glob = "0.3"
temp-file = "0.1"
